//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlucaTrack.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlucaTrack.Website.Resources.Account_Strings", typeof(Account_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Button_ChangePassword {
            get {
                return ResourceManager.GetString("Button_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Registration.
        /// </summary>
        internal static string Button_FinishRegistration {
            get {
                return ResourceManager.GetString("Button_FinishRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Sign in    .
        /// </summary>
        internal static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Save Settings   .
        /// </summary>
        internal static string Button_SavePersonalSettings {
            get {
                return ResourceManager.GetString("Button_SavePersonalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string Button_SendEmail {
            get {
                return ResourceManager.GetString("Button_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;GlucaTrack Reset Password Request&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;We hear you forgot your password.  Dont worry, click the following URL or copy/paste the link into your browser&apos;s URL address to set your new password:&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        internal static string Email_ResetPasswordBody {
            get {
                return ResourceManager.GetString("Email_ResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlucaTrack Password Reset Request.
        /// </summary>
        internal static string Email_ResetPasswordSubject {
            get {
                return ResourceManager.GetString("Email_ResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Step 1.
        /// </summary>
        internal static string Header_RegistrationStep1 {
            get {
                return ResourceManager.GetString("Header_RegistrationStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        internal static string Label_Address1 {
            get {
                return ResourceManager.GetString("Label_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1 is required..
        /// </summary>
        internal static string Label_Address1_RequiredError {
            get {
                return ResourceManager.GetString("Label_Address1_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        internal static string Label_Address2 {
            get {
                return ResourceManager.GetString("Label_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string Label_Birthdate {
            get {
                return ResourceManager.GetString("Label_Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate is required..
        /// </summary>
        internal static string Label_Birthdate_RequiredError {
            get {
                return ResourceManager.GetString("Label_Birthdate_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Label_City {
            get {
                return ResourceManager.GetString("Label_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        internal static string Label_City_RequiredError {
            get {
                return ResourceManager.GetString("Label_City_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required..
        /// </summary>
        internal static string Label_ConfirmPassword_RequiredError {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required..
        /// </summary>
        internal static string Label_Country_RequiredError {
            get {
                return ResourceManager.GetString("Label_Country_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of diabetes.
        /// </summary>
        internal static string Label_DiabetesType {
            get {
                return ResourceManager.GetString("Label_DiabetesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes type is required..
        /// </summary>
        internal static string Label_DiabetesType_RequiredError {
            get {
                return ResourceManager.GetString("Label_DiabetesType_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string Label_DontHaveAccount {
            get {
                return ResourceManager.GetString("Label_DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string Label_EmailAddress {
            get {
                return ResourceManager.GetString("Label_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string Label_EmailAddress_RequiredError {
            get {
                return ResourceManager.GetString("Label_EmailAddress_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format..
        /// </summary>
        internal static string Label_EmailFormat_Error {
            get {
                return ResourceManager.GetString("Label_EmailFormat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address entered.  No user exists with that email address..
        /// </summary>
        internal static string Label_EmailInvalid_Error {
            get {
                return ResourceManager.GetString("Label_EmailInvalid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;Email Sent Successfully.  You should receive an email shortly with a reset password link in it.&lt;br/&gt;&lt;br/&gt;Click on this link and you will be able to reset your password.&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        internal static string Label_EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("Label_EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Label_Firstname {
            get {
                return ResourceManager.GetString("Label_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        internal static string Label_Firstname_RequiredError {
            get {
                return ResourceManager.GetString("Label_Firstname_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See you later, {0}..
        /// </summary>
        internal static string Label_GoodbyeMessage {
            get {
                return ResourceManager.GetString("Label_GoodbyeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High end of normal.
        /// </summary>
        internal static string Label_HighNormal {
            get {
                return ResourceManager.GetString("Label_HighNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Range.
        /// </summary>
        internal static string Label_IncomeRange {
            get {
                return ResourceManager.GetString("Label_IncomeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Range is required..
        /// </summary>
        internal static string Label_IncomeRange_RequiredError {
            get {
                return ResourceManager.GetString("Label_IncomeRange_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Label_Lastname {
            get {
                return ResourceManager.GetString("Label_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        internal static string Label_Lastname_RequiredError {
            get {
                return ResourceManager.GetString("Label_Lastname_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sync.
        /// </summary>
        internal static string Label_LastSync {
            get {
                return ResourceManager.GetString("Label_LastSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logged into website.
        /// </summary>
        internal static string Label_LastWebLogin {
            get {
                return ResourceManager.GetString("Label_LastWebLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low end of normal.
        /// </summary>
        internal static string Label_LowNormal {
            get {
                return ResourceManager.GetString("Label_LowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        internal static string Label_Middlename {
            get {
                return ResourceManager.GetString("Label_Middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name is required..
        /// </summary>
        internal static string Label_Middlename_RequiredError {
            get {
                return ResourceManager.GetString("Label_Middlename_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string Label_Password_RequiredError {
            get {
                return ResourceManager.GetString("Label_Password_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was changed successfully.  Next time you login you will be required to use this new password..
        /// </summary>
        internal static string Label_PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("Label_PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string Label_PasswordCompare_Error {
            get {
                return ResourceManager.GetString("Label_PasswordCompare_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 nonblank characters..
        /// </summary>
        internal static string Label_PasswordLength_Error {
            get {
                return ResourceManager.GetString("Label_PasswordLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string Label_Race {
            get {
                return ResourceManager.GetString("Label_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race is required..
        /// </summary>
        internal static string Label_Race_RequiredError {
            get {
                return ResourceManager.GetString("Label_Race_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now.
        /// </summary>
        internal static string Label_RegisterLink {
            get {
                return ResourceManager.GetString("Label_RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information will help us trend data across the world geographically..
        /// </summary>
        internal static string Label_Registration2MessageInfo {
            get {
                return ResourceManager.GetString("Label_Registration2MessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of 6 characters in length..
        /// </summary>
        internal static string Label_RegistrationMessageInfo {
            get {
                return ResourceManager.GetString("Label_RegistrationMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string Label_RememberMe {
            get {
                return ResourceManager.GetString("Label_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex/Gender.
        /// </summary>
        internal static string Label_Sex {
            get {
                return ResourceManager.GetString("Label_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex is required..
        /// </summary>
        internal static string Label_Sex_RequiredError {
            get {
                return ResourceManager.GetString("Label_Sex_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start afternoon.
        /// </summary>
        internal static string Label_StartAfternoon {
            get {
                return ResourceManager.GetString("Label_StartAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start morning.
        /// </summary>
        internal static string Label_StartMorning {
            get {
                return ResourceManager.GetString("Label_StartMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start night.
        /// </summary>
        internal static string Label_StartNight {
            get {
                return ResourceManager.GetString("Label_StartNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province/Region.
        /// </summary>
        internal static string Label_State {
            get {
                return ResourceManager.GetString("Label_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required..
        /// </summary>
        internal static string Label_State_RequiredError {
            get {
                return ResourceManager.GetString("Label_State_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        internal static string Label_Timezone {
            get {
                return ResourceManager.GetString("Label_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone is required..
        /// </summary>
        internal static string Label_Timezone_RequiredError {
            get {
                return ResourceManager.GetString("Label_Timezone_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required..
        /// </summary>
        internal static string Label_Username_RequiredError {
            get {
                return ResourceManager.GetString("Label_Username_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account type.
        /// </summary>
        internal static string Label_UserType {
            get {
                return ResourceManager.GetString("Label_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}, Registration is complete.  You will now be redirected to the main page..
        /// </summary>
        internal static string Label_WelcomeRegistrationComplete {
            get {
                return ResourceManager.GetString("Label_WelcomeRegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/Postal Code.
        /// </summary>
        internal static string Label_Zipcode {
            get {
                return ResourceManager.GetString("Label_Zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode is required..
        /// </summary>
        internal static string Label_Zipcode_RequiredError {
            get {
                return ResourceManager.GetString("Label_Zipcode_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Link_ResetPassword {
            get {
                return ResourceManager.GetString("Link_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        internal static string Login_Failure {
            get {
                return ResourceManager.GetString("Login_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string Month_1 {
            get {
                return ResourceManager.GetString("Month_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string Month_10 {
            get {
                return ResourceManager.GetString("Month_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Month_11 {
            get {
                return ResourceManager.GetString("Month_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Month_12 {
            get {
                return ResourceManager.GetString("Month_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feburary.
        /// </summary>
        internal static string Month_2 {
            get {
                return ResourceManager.GetString("Month_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string Month_3 {
            get {
                return ResourceManager.GetString("Month_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Month_4 {
            get {
                return ResourceManager.GetString("Month_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Month_5 {
            get {
                return ResourceManager.GetString("Month_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string Month_6 {
            get {
                return ResourceManager.GetString("Month_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string Month_7 {
            get {
                return ResourceManager.GetString("Month_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string Month_8 {
            get {
                return ResourceManager.GetString("Month_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Month_9 {
            get {
                return ResourceManager.GetString("Month_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username available!.
        /// </summary>
        internal static string Username_Available {
            get {
                return ResourceManager.GetString("Username_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can not be blank..
        /// </summary>
        internal static string Username_Blank {
            get {
                return ResourceManager.GetString("Username_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username taken, sorry..
        /// </summary>
        internal static string Username_NotAvailable {
            get {
                return ResourceManager.GetString("Username_NotAvailable", resourceCulture);
            }
        }
    }
}
