//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlucaTrack.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlucaTrack.Website.Resources.Content_Strings", typeof(Content_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg: .
        /// </summary>
        internal static string Label_Average {
            get {
                return ResourceManager.GetString("Label_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   (&gt; {0}).
        /// </summary>
        internal static string Label_HighExplanation {
            get {
                return ResourceManager.GetString("Label_HighExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   (&lt; {0}).
        /// </summary>
        internal static string Label_LowExplanation {
            get {
                return ResourceManager.GetString("Label_LowExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: .
        /// </summary>
        internal static string Label_Maximum {
            get {
                return ResourceManager.GetString("Label_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min: .
        /// </summary>
        internal static string Label_Minimum {
            get {
                return ResourceManager.GetString("Label_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # High: .
        /// </summary>
        internal static string Label_NumberOfHighs {
            get {
                return ResourceManager.GetString("Label_NumberOfHighs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Low: .
        /// </summary>
        internal static string Label_NumberOfLows {
            get {
                return ResourceManager.GetString("Label_NumberOfLows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year.
        /// </summary>
        internal static string Option_1year {
            get {
                return ResourceManager.GetString("Option_1year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 days.
        /// </summary>
        internal static string Option_30days {
            get {
                return ResourceManager.GetString("Option_30days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3d Graphs.
        /// </summary>
        internal static string Option_3DGraphs {
            get {
                return ResourceManager.GetString("Option_3DGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        internal static string Option_7days {
            get {
                return ResourceManager.GetString("Option_7days", resourceCulture);
            }
        }
    }
}
