//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlucaTrack.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlucaTrack.Website.Resources.Content_Strings", typeof(Content_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AxisLabel_X_MainGraph {
            get {
                return ResourceManager.GetString("AxisLabel_X_MainGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose.
        /// </summary>
        internal static string AxisLabel_Y_MainGraph {
            get {
                return ResourceManager.GetString("AxisLabel_Y_MainGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Settings.
        /// </summary>
        internal static string Button_PersonalSettings {
            get {
                return ResourceManager.GetString("Button_PersonalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose Trending Over The Last {0} Days.
        /// </summary>
        internal static string GraphTitle_Main {
            get {
                return ResourceManager.GetString("GraphTitle_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoons.
        /// </summary>
        internal static string GraphTitle_PieAfternoons {
            get {
                return ResourceManager.GetString("GraphTitle_PieAfternoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mornings.
        /// </summary>
        internal static string GraphTitle_PieMornings {
            get {
                return ResourceManager.GetString("GraphTitle_PieMornings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nights.
        /// </summary>
        internal static string GraphTitle_PieNights {
            get {
                return ResourceManager.GetString("GraphTitle_PieNights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg: .
        /// </summary>
        internal static string Label_Average {
            get {
                return ResourceManager.GetString("Label_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics and HbA1c / eAG.
        /// </summary>
        internal static string Label_GraphsAndGaugesSectionHeader {
            get {
                return ResourceManager.GetString("Label_GraphsAndGaugesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   (&gt; {0}).
        /// </summary>
        internal static string Label_HighExplanation {
            get {
                return ResourceManager.GetString("Label_HighExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   (&lt; {0}).
        /// </summary>
        internal static string Label_LowExplanation {
            get {
                return ResourceManager.GetString("Label_LowExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose Trending Over the Last {0} Days.
        /// </summary>
        internal static string Label_MainGraphSectionHeader {
            get {
                return ResourceManager.GetString("Label_MainGraphSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: .
        /// </summary>
        internal static string Label_Maximum {
            get {
                return ResourceManager.GetString("Label_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min: .
        /// </summary>
        internal static string Label_Minimum {
            get {
                return ResourceManager.GetString("Label_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available for this period..
        /// </summary>
        internal static string Label_Nodata {
            get {
                return ResourceManager.GetString("Label_Nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # High: .
        /// </summary>
        internal static string Label_NumberOfHighs {
            get {
                return ResourceManager.GetString("Label_NumberOfHighs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Low: .
        /// </summary>
        internal static string Label_NumberOfLows {
            get {
                return ResourceManager.GetString("Label_NumberOfLows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose Readings.
        /// </summary>
        internal static string Label_RawValuesSectionHeader {
            get {
                return ResourceManager.GetString("Label_RawValuesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StdDev: .
        /// </summary>
        internal static string Label_StandardDeviation {
            get {
                return ResourceManager.GetString("Label_StandardDeviation", resourceCulture);
            }
        }
    }
}
