//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlucaTrack.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlucaTrack.Website.Resources.General_Strings", typeof(General_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply plug in your supported glucometer to your computer and sit back and relax. No more dried up pens or fumbling with that old logbook..
        /// </summary>
        internal static string Label_FirstContent {
            get {
                return ResourceManager.GetString("Label_FirstContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy and Simple.
        /// </summary>
        internal static string Label_FirstTitle {
            get {
                return ResourceManager.GetString("Label_FirstTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an investment in yourself by making more informed decisions for a healthier life. Take control of your diabetes by viewing, and acting upon trends spotted on your personalized graphical dashboard..
        /// </summary>
        internal static string Label_FourthContent {
            get {
                return ResourceManager.GetString("Label_FourthContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Life.
        /// </summary>
        internal static string Label_FourthTitle {
            get {
                return ResourceManager.GetString("Label_FourthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether you use one brand of meter or have several at home, work and in the car, bring all of your records together in one place accessible from anywhere..
        /// </summary>
        internal static string Label_SecondContent {
            get {
                return ResourceManager.GetString("Label_SecondContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidate.
        /// </summary>
        internal static string Label_SecondTitle {
            get {
                return ResourceManager.GetString("Label_SecondTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe, secure, encrypted. Sleep easy knowing your information is protected with AES-256bit data encryption and transported via 128bit SSL..
        /// </summary>
        internal static string Label_ThirdContent {
            get {
                return ResourceManager.GetString("Label_ThirdContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe and Secure.
        /// </summary>
        internal static string Label_ThirdTitle {
            get {
                return ResourceManager.GetString("Label_ThirdTitle", resourceCulture);
            }
        }
    }
}
