//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlucaTrack.Services.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58F9D95D80A441388F41642E5B169191")]
        public string Encrypt_Key1 {
            get {
                return ((string)(this["Encrypt_Key1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AA1CDB2242C74EAF859E531987408CCE")]
        public string Encrypt_Key2 {
            get {
                return ((string)(this["Encrypt_Key2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("626D54F10AAC442AA24E6CE65FE92B4F")]
        public string Encrypt_Key3 {
            get {
                return ((string)(this["Encrypt_Key3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104FB99E06A040878E7EF56DB0D85729")]
        public string Encrypt_Key4 {
            get {
                return ((string)(this["Encrypt_Key4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E85F25B6E6064E2685F1DE592B851F7B")]
        public string Encrypt_Key5 {
            get {
                return ((string)(this["Encrypt_Key5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CF3F72F5B97D47C3B7C443D79EDEF157")]
        public string Encrypt_Key6 {
            get {
                return ((string)(this["Encrypt_Key6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800E56F2F7C4CA0BD106477E2E38A79")]
        public string Encrypt_Key7 {
            get {
                return ((string)(this["Encrypt_Key7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7CC4AE6825684A5E9738A09328350944")]
        public string Encrypt_Key8 {
            get {
                return ((string)(this["Encrypt_Key8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15514619A56A41B08469190A83449336")]
        public string Encrypt_Key9 {
            get {
                return ((string)(this["Encrypt_Key9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25667027EFBF4887B1B8561B2985D983")]
        public string Encrypt_Key10 {
            get {
                return ((string)(this["Encrypt_Key10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4BB815BEDEBF4725A60C21A722F7A799")]
        public string Encrypt_Key11 {
            get {
                return ((string)(this["Encrypt_Key11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7FA79CE511FD484088BEE3690CA37BC3")]
        public string Encrypt_Key12 {
            get {
                return ((string)(this["Encrypt_Key12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B6EEF5B4A9C54A06A2AA5AD34A061314")]
        public string Encrypt_Key13 {
            get {
                return ((string)(this["Encrypt_Key13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("98B6AE7778864BA2AF08297D01B6DA4F")]
        public string Encrypt_Key14 {
            get {
                return ((string)(this["Encrypt_Key14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("750D1E0852014D43AC9848E336C95646")]
        public string Encrypt_Key15 {
            get {
                return ((string)(this["Encrypt_Key15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C105B22AFCCA4429A5C622DAD87C636B")]
        public string Encrypt_Key16 {
            get {
                return ((string)(this["Encrypt_Key16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0CCD3827AEB64A728203AAE50F299E6C")]
        public string Encrypt_Key17 {
            get {
                return ((string)(this["Encrypt_Key17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BF29572521A34271B09E6C482D9B9CFE")]
        public string Encrypt_Key18 {
            get {
                return ((string)(this["Encrypt_Key18"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7C4566E5AE224C6CB8D048D26946EDE9")]
        public string Encrypt_Key19 {
            get {
                return ((string)(this["Encrypt_Key19"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3DA37242B30B478CAAB62BDD50E82F2A")]
        public string Encrypt_Key20 {
            get {
                return ((string)(this["Encrypt_Key20"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3B78F9C7FFCE4DAEA39AE38E4206D76E")]
        public string Encrypt_Key21 {
            get {
                return ((string)(this["Encrypt_Key21"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("972AD941208940CA8B838977B7B9EFA1")]
        public string Encrypt_Key22 {
            get {
                return ((string)(this["Encrypt_Key22"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99FD0B26B5174CB5B5B8A9446212548A")]
        public string Encrypt_Key23 {
            get {
                return ((string)(this["Encrypt_Key23"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B3ED9ECC534B4F1DA8648B363AF21793")]
        public string Encrypt_Key24 {
            get {
                return ((string)(this["Encrypt_Key24"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4AC808147F23454AA886D9545374E312")]
        public string Encrypt_Key25 {
            get {
                return ((string)(this["Encrypt_Key25"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14089462B97840DD9680E55761D10594")]
        public string Encrypt_Key26 {
            get {
                return ((string)(this["Encrypt_Key26"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BA96D8CA8BA342C8A2FC19EF00AF82D7")]
        public string Encrypt_Key27 {
            get {
                return ((string)(this["Encrypt_Key27"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2DD46AF425C4948A9895ABB6E787C89")]
        public string Encrypt_Key28 {
            get {
                return ((string)(this["Encrypt_Key28"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6D3F732F4BEC4865814E999A8583B86C")]
        public string Encrypt_Key29 {
            get {
                return ((string)(this["Encrypt_Key29"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("69076172AFAF4EADABFB810EE2FD1813")]
        public string Encrypt_Key30 {
            get {
                return ((string)(this["Encrypt_Key30"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("309938A6D18C4039BAECCA1C6C2277A5")]
        public string Encrypt_Key31 {
            get {
                return ((string)(this["Encrypt_Key31"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E441699041D7434797DBBF1493A5C15A")]
        public string defaultKey {
            get {
                return ((string)(this["defaultKey"]));
            }
        }
    }
}
